- name: Demo on variables
  hosts: all
  vars:
    URL: google.com
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: "URL= {{URL}}"
    - name: Print task variable    
      ansible.builtin.debug:
        msg: "URL={{URL}}"
      vars:
        URL: taks.google.com

- name: Demo on variables
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Print file variable
      ansible.builtin.debug:
        msg: "URL= {{URL}}"
  