- name: Demo on variables
  hosts: all
  vars:
    URL: google.com
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: "URL= {{URL}}"
    - name: Print task variable    
      ansible.builtin.debug:
        msg: "URL={{URL}}"
      vars:
        URL: taks.google.com

- name: Demo on variables
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Print file variable
      ansible.builtin.debug:
        msg: "URL= {{URL}}"

- name: Demo on paly3
  hosts: all
  gather_fact: no
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: "URL= {{URL}}"
      vars:
        URL: task.google.com

- name: Demo on paly4
  hosts: all
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: "Hostname= {{ansible_fqdn}}"

- name: Demo on paly5
  hosts: all
  tasks:
    - name: Print variable command
      ansible.builtin.shell: uptime
      register: out