help:           ## Show this help.
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
frontend: ## Installing Frontend Component
	@echo Installing Frontend
catalogue: ## Installing Catalogue Component
	@echo Installing Catalogue
cart: ## Installing Cart Component
	@echo Installing Cart
shipping: ## Installing Shipping Component
	@echo Installing Shipping
user: ## Installing User Component
	@echo Installing User
payment: ## Installing Payment Component
	@echo Installing Payment
redis: ## Installing Redis Component
	@echo Installing Redis
mysql: ## Installing Mysql Component
	@echo Installing Mysql
rabbitmq: ## Installing Rabbitmq Component
	@echo Installing Rabbitmq..
mongodb: ## Installing Mongodb Component
	@echo Installing Mongodb..
	
	