frontend:
	@echo Installing frontend..
catalogue:
	@echo Installing catalogue..
cart:
	@echo Installing cart..
shipping:
	@echo Installing shipping..
user:
	@echo Installing user..
payment:
	@echo Installing payment..
redis:
	@echo Installing redis..
mysql:
	@echo Installing mysql..
rabbitmq:
	@echo Installing rabbitmq..
mongodb:
	@echo Installing mongodb..
	
	